const char *gfx_source =
""
""
"\n#version 130\n"
""
"out vec4 gl_FragColor;"
""
"const vec2 E=vec2 (1920,1080);"
"const float f1=4.;"
""
"const float w1=acos(-1.);"
"const vec3 m=vec3 (1.,0.,-1.);"
"const float M=.45;"
""
""
"void j(in vec2 y,out float n)"
"{"
"vec3 T=fract(vec3 (y.xyx)*.1031);"
"T+=dot(T,T.yzx+33.33);"
"n=fract((T.x+T.y)*T.z);"
"}"
""
"void d1(in float y,out float n)"
"{"
"y=fract(y*.1031);"
"y*=y+33.33;"
"y*=y+y;"
"n=fract(y);"
"}"
""
"void g(in float f,out float a)"
"{"
"float l=floor(f);"
"f=fract(f);"
"vec2 t;"
"d1(1.e2*l,t.x);"
"d1(1.e2*(l+1.),t.y);"
"a=mix(t.x,t.y,smoothstep(0.,1.,f));"
"a=-1.+2.*a;"
"}"
""
"void s1(in vec2 o,out vec2 x)"
"{"
"x=vec2 (length(o),atan(o.y,o.x));"
"}"
""
"void t1(in vec2 o,out vec2 x)"
"{"
"x=o.x*vec2 (cos(o.y),sin(o.y));"
"}"
""
"void x1(in vec2 n1,in vec2 r1,out vec2 w)"
"{"
"w=(n1.x<r1.x)?n1:r1;"
"}"
""
""
"float N1(in float n)"
"{"
"return smoothstep(1.5/E.y,-1.5/E.y,n);"
"}"
""
"void S(in vec3 o,out vec2 w)"
"{"
""
"const float M=.4;"
"float t,h,U;"
""
"w=vec2 (o.z+M,0.);"
""
"g(2.*o.x,h);"
""
"o.yz*=1.+.4*h;"
""
""
"float d=2.*o.x-h;"
"mat2 A=mat2 (cos(d),sin(d),-sin(d),cos(d));"
"o.yz=A*o.yz;"
""
"vec2 C,"
"k=vec2 (.02,w1/16.),"
"x;"
"s1(o.yz,C);"
"vec2 B=mod(C,k)-.5*k,"
"u=C-B;"
"t1(u,x);"
""
"j(u,t);"
"j(u+1337.,U);"
""
"if(u.x<.3&&U<.2)"
"{"
"vec2 z;"
"g(12.*o.x+1337.*t,z.x);"
"g(12.*o.x+2337.*t,z.y);"
"x1(w,vec2 (length((o.yz-x-.005*z))-.02*(.125),2.+floor(6.*t)),w);"
"}"
""
"g(2.*o.x-1337.,h);"
"d=2.*o.x-h;"
"A=mat2 (cos(d),-sin(d),sin(d),cos(d));"
"o.yz=A*A*o.yz;"
"o.x+=1337.;"
"s1(o.yz,C);"
"B=mod(C,k)-.5*k;"
"u=C-B;"
"t1(u,x);"
""
"j(u,t);"
"j(u+1337.,U);"
""
"if(u.x<.2&&U<.2)"
"{"
"vec2 z;"
"g(12.*o.x+1337.*t,z.x);"
"g(12.*o.x+2337.*t,z.y);"
"x1(w,vec2 (length((o.yz-x-.005*z))-.02*(.125),2.+floor(6.*t)),w);"
"}"
"}"
""
""
"float l1(in vec3 o)"
"{"
"float h;"
"g(2.*o.x,h);"
"o.yz*=1.+.4*h;"
"float d=2.*o.x-h;"
"mat2 A=mat2 (cos(d),sin(d),-sin(d),cos(d));"
"o.yz=A*o.yz;"
"return length(o.yz)-.4;"
"}"
""
"\n#define z1(s,f)void s(in vec3 o,out vec3 a,in float D){vec2 i,N;f(o,i);f(o+D*m.xyy,N);a.x=N.x;f(o+D*m.yxy,N);a.y=N.x;f(o+D*m.yyx,N);a.z=N.x;a=normalize(a-i.x);}\n"
"z1(W,S)"
""
"\n#define c1(h1,u1,b1,step)void h1(out vec3 o,in vec3 s,inout float n,in vec3 c,in int b,out int l,out vec2 i){for(l=0;l<b;++l){o=s+n*c;u1(o,i);if(i.x<1.e-4)return ;if(b1){l=b;}n+=step;}}\n"
"c1(a1,S,false,min(i.x,mix(2.e-1,1.e-3,step(l1(o),0.))))"
"c1(R1,S,l1(o)>0.,min(i.x,1.e-2))"
""
"void G(in vec3 o,in vec3 a,in vec3 c,in vec3 r,inout vec3 e,in vec2 i)"
"{"
"if(i.y==0.){"
"e=vec3 (.05,.08,.15);"
"e=.1*e"
"+.8*e*max(dot(r-o,a),0.)"
"+.5*e*pow(max(dot(reflect(r-o,a),c),0.),2.);"
"}"
"else if(i.y==1.){"
"e=.4*m.xxx;"
"e=.6*e"
"+.8*e*max(dot(r-o,a),0.)"
"+1.5*e*pow(max(dot(reflect(r-o,a),c),0.),2.);"
"}"
"else if(i.y==2.)"
"{"
"e=vec3 (0.18,0.14,0.19);"
"e=.7*e"
"+.8*e*max(dot(r-o,a),0.)"
"+.3*e*pow(max(dot(reflect(r-o,a),c),0.),1.);"
"}"
"else if(i.y==3.)"
"{"
"e=vec3 (0.29,0.27,0.47);"
"e=.7*e"
"+.8*e*max(dot(r-o,a),0.)"
"+.3*e*pow(max(dot(reflect(r-o,a),c),0.),1.);"
"}"
"else if(i.y==4.)"
"{"
"e=vec3 (0.62,0.44,0.62);"
"e=.7*e"
"+.8*e*max(dot(r-o,a),0.)"
"+.3*e*pow(max(dot(reflect(r-o,a),c),0.),1.);"
"}"
"else if(i.y==5.)"
"{"
"e=vec3 (0.87,0.24,0.59);"
"e=.7*e"
"+.8*e*max(dot(r-o,a),0.)"
"+.3*e*pow(max(dot(reflect(r-o,a),c),0.),1.);"
"}"
"else if(i.y==6.)"
"{"
"e=vec3 (0.72,0.17,0.42);"
"e=.7*e"
"+.8*e*max(dot(r-o,a),0.)"
"+.3*e*pow(max(dot(reflect(r-o,a),c),0.),1.);"
"}"
"else if(i.y==7.)"
"{"
"e=vec3 (0.59,0.07,0.29);"
"e=.7*e"
"+.8*e*max(dot(r-o,a),0.)"
"+.3*e*pow(max(dot(reflect(r-o,a),c),0.),1.);"
"}"
"}"
""
"void p1(out vec4 v1,in vec2 y1)"
"{"
"vec2 i1=(y1-.5*E.xy)/E.y,"
"i,g1,"
"H;"
"vec3 e=m.yyy,"
"s=2.*m.zzx-.4*m.yyx+.05*m.zzy,"
"e1=s,"
"t=m.xzy,"
"f=m.yyy,"
"m1=cross(normalize(f-s),-t),"
"c,"
"a,"
"o,"
"p=m.yyy,"
"r,"
"P,"
"L,"
"R,"
"o1,"
"O;"
"int b=4000,"
"l;"
"float n=0.,K;"
""
"f+=i1.x*t+i1.y*m1;"
"c=normalize(f-s);"
""
"a1(o,s,n,c,b,l,i);"
""
"r=m.yyx;"
"P=m.xzx;"
""
"if(l<b)"
"{"
"W(o,a,5.e-5);"
"a=round(a);"
"}"
"else "
"{"
"n=-(s.z+M)/c.z;"
"o=s+n*c;"
"S(o,i);"
"W(o,a,5.e-5);"
"a=round(a);"
"}"
""
"G(o,a,c,r,e,i);"
"G(o,a,c,P,p,i);"
"e=mix(e,p,.5);"
""
"if(i.y==0.)"
"{"
"e1=o;"
"L=reflect(c,a);"
"K=.01;"
"a1(R,e1,K,L,b,l,H);"
""
"if(l<b)"
"{"
"W(R,O,5.e-4);"
"a=round(a);"
"G(R,O,L,r,p,H);"
"G(R,O,L,P,o1,H);"
"p=mix(p,o1,.5);"
"e=mix(e,p,.4);"
"}"
"}"
""
"R=o;"
""
"s=o;"
"c=normalize(r-o);"
"n=1.e-2;"
""
"{"
"float v=1.0;"
"float F=1.e20;"
"for(int l=0;l<b;++l)"
"{"
"o=s+n*c;"
"S(o,i);"
"if(i.x<1.e-4)"
"{"
"v=0.;"
"break;"
"}"
"if(o.z>.5)break;"
"float x=i.x*i.x/(2.0*F);"
"float q=sqrt(i.x*i.x-x*x);"
"v=min(v,100.0*q/max(0.0,n-x));"
"F=i.x;"
"n+=min(i.x,5.e-3);"
"}"
"e=mix(.3*e,e,v);"
"}"
""
"o=R;"
"s=o;"
"c=normalize(P-o);"
"n=1.e-2;"
""
"{"
"float v=1.0;"
"float F=1.e20;"
"for(int l=0;l<b;++l)"
"{"
"o=s+n*c;"
"S(o,i);"
"if(i.x<1.e-4)"
"{"
"v=0.;"
"break;"
"}"
"if(o.z>.5)break;"
"float x=i.x*i.x/(2.0*F);"
"float q=sqrt(i.x*i.x-x*x);"
"v=min(v,100.0*q/max(0.0,n-x));"
"F=i.x;"
"n+=min(i.x,5.e-3);"
"}"
"e=mix(.3*e,e,v);"
"}"
""
"e=e+1.*e*e*e;"
""
"v1=vec4 (clamp(e,0.,1.),1.);"
"}"
""
"void main()"
"{"
"vec4 e=vec4 (0.);"
"float I=sqrt(f1)-1.;"
"for(float l=-.5*I;l<=.5*I;l+=1.)"
"for(float Y=-.5*I;Y<=.5*I;Y+=1.)"
"{"
"vec4 p;"
"p1(p,gl_FragCoord.xy+vec2 (l,Y)*1./max(I,1.));"
"e+=p;"
"}"
"e/=f1;"
"gl_FragColor=e;"
"}"
""
;
